name: Deploy FastAPI App

on:
  push:
    branches:
      - main  # Runs the deployment pipeline when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${SERVER_USER}@${SERVER_IP} << EOF
            cd /path/to/your/project
            git pull origin main
            source /path/to/your/venv/bin/activate
            pip install -r requirements.txt
            systemctl restart fastapi
            systemctl restart nginx
          EOF
