name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          ssh user@server-ip 'cd /path/to/app && git pull origin main && systemctl restart fastapi.service'
